export const REQUEST_CREATE_REQUEST="REQUEST_CREATE_REQUEST"
export const REQUEST_CREATE_SUCCESS="REQUEST_CREATE_SUCCESS"
export const REQUEST_CREATE_FAILURE="REQUEST_CREATE_FAILURE"

export const REQUEST_DELETE_REQUEST="REQUEST_DELETE_REQUEST"
export const REQUEST_DELETE_SUCCESS="REQUEST_DELETE_SUCCESS"
export const REQUEST_DELETE_FAILURE="REQUEST_DELETE_FAILURE"

export const GET_ALL_REQUESTS_REQUEST="GET_ALL_REQUESTS_REQUEST"
export const GET_ALL_REQUESTS_SUCCESS="GET_ALL_REQUESTS_SUCCESS"
export const GET_ALL_REQUESTS_FAILURE="GET_ALL_REQUESTS_FAILURE"


export const GET_USERS_REQUEST_REQUEST="GET_USERS_REQUEST_REQUEST"
export const GET_USERS_REQUEST_SUCCESS="GET_USERS_REQUEST_SUCCESS"
export const GET_USERS_REQUEST_FAILURE="GET_USERS_REQUEST_FAILURE"

// export const GET_USER_LIKE_REQUEST="GET_USERS_LIKE_REQUEST"
// export const GET_USER_LIKE_SUCCESS="GET_USERS_LIKE_SUCCESS"
// export const GET_USER_LIKE_FAILURE="GET_USERS_LIKE_FAILURE"



export const  USER_LIKE_REQUEST_REQUEST=" USER_LIKE_REQUEST_REQUEST"
export const  USER_LIKE_REQUEST_SUCCESS=" USER_LIKE_REQUEST_SUCCESS"
export const  USER_LIKE_REQUEST_FAILURE=" USER_LIKE_REQUEST_FAILURE"

export const  LIKE_REQUEST_REQUEST=" LIKE_REQUEST_REQUEST"
export const  LIKE_REQUEST_SUCCESS=" LIKE_REQUEST_SUCCESS"
export const  LIKE_REQUEST_FAILURE=" LIKE_REQUEST_FAILURE"

export const  FIND_REQUEST_BY_ID_REQUEST=" FIND_REQUEST_BY_ID_REQUEST"
export const  FIND_REQUEST_BY_ID_SUCCESS=" FIND_REQUEST_BY_ID_SUCCESS"
export const  FIND_REQUEST_BY_ID_FAILURE=" FIND_REQUEST_BY_ID_FAILURE"


export const  OFFRE_REQUEST=" OFFRE_REQUEST"
export const  OFFRE_SUCCESS=" OFFRE_SUCCESS"
export const  OFFRE_FAILURE=" OFFRE_FAILURE"


export const REQUEST_COPY_REQUEST="REQUEST_COPY_REQUEST"
export const REQUEST_COPY_SUCCESS="REQUEST_COPY_SUCCESS"
export const REQUEST_COPY_FAILURE="REQUEST_COPY_FAILURE"

